# Generated by Django 5.2.8 on 2025-11-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('address_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address_types',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=255)),
                ('page_content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('phone_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phone_types',
            },
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('web_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_users',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('web_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_user.webuser')),
            ],
            options={
                'db_table': 'user_infos',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_user.phonetype')),
                ('web_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_user.webuser')),
            ],
            options={
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_user.addresstype')),
                ('web_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_user.webuser')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
